# Generated by Django 4.2.5 on 2023-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(default='available', max_length=10)),
            ],
        ),
    ]
